### PR TITLE
CMakeLists: fix clang SSE detection

### PR DESCRIPTION
**Pull request by chouquette**
When passing -msse to clang, it only issues a warning which causes a false positive for SSE detection. This will cause build failures later on if the targeted architecture isn't X86

### CODE REVIEW

**Comment by chouquette** [comment]
This should help with #266 and #308

**Comment by chouquette** [comment]
> A cleaner approach might be to replace the cmake variable `DISABLE_SSE` which you probably should have set for a non-x86 architecture with an automatic detection of an x86 target.

That also works for me. To clarify, do you mean to discard the changes from this PR and update the `DISABLE_SSL` default value to something like "arch != x86" ? Or update that default value in addition to ensuring the check doesn't lead to a false positive?

**Comment by chouquette** [comment]
I'd argue that it's quite handy to be able to disable hardware accelerations, especially on some platforms such as wasm/nasm, but I can live with converting `DISABLE_SSE` from an option to an internal variable

**Comment by chouquette** [comment]
Alternative implementation submitted: https://github.com/strukturag/libde265/pull/411

**Comment by farindk** [comment]
Merged PR #410 instead

**Pull request closed without merging**
