### PR TITLE
Use libde265_min and libde265_max

### PR DESCRIPTION
**Pull request by dlemstra**
This PR changes `std::min` to `libde265_min` and `std::max` to `libde265_max`.  We use this library inside the @ImageMagick project and our build fails without these changes.

### CODE REVIEW

**Comment by dlemstra** [comment]
Not sure if we still need this change or maybe we should remove `libde265_min` and `libde265_max`.

p.s. I completely forgot I already reported issues forthis build problem.

**Comment by farindk** [comment]
I just cleaned up the messy branches on our side. Current version is now in the 'master' branch.
If the current `master` works for you, we do not need this PR.

**Comment by dlemstra** [comment]
The `NOMINMAX` define should resolve the issues. Looking forward to a new release :wink:

**Comment by farindk** [comment]
Released this as v1.0.5

**Comment by dlemstra** [comment]
Thanks for the quick release.

**Pull request closed without merging**
