### PR TITLE
Add CMake options ENABLE_DECODER and ENABLE_ENCODER

### PR DESCRIPTION
**Pull request by heitbaum**
Update make to allow build with/without Decoder or Encoder.
Default to building (as-is currently the case)

### CODE REVIEW

**Comment by heitbaum** [comment]
@farindk - updated the PR to match your https://github.com/strukturag/libde265/pull/331/commits/296130f382c2822f819be14373343044483c8dd4 commit. Tested with 1.0.9.

**Comment by farindk** [comment]
Thank you.

**Comment by fancycode** [comment]
@farindk this broke the windows CI which is expecting the enc265.exe to exist:
https://github.com/strukturag/libde265/blob/757f450c81cb2b298eab7420c6bcfab148c4f427/appveyor.yml#L33

Example failure: https://ci.appveyor.com/project/strukturag/libde265/build/job/86sp8krn9hvr50ht

**Comment by farindk** [comment]
@fancycode Can you exclude `enc265.exe` from the Windows CI? The encoder is not in a usable state, nobody is using it, and that probably won't change anytime soon.

**Pull request merged**
